.PHONY: all clean

UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Linux)
	FC = ifx
	FFLAGS = -O3 -std=legacy -fPIC
	LDFLAGS =
else
	FC = ifx
	FFLAGS = -O3 -std=legacy
	LDFLAGS =
endif

all:
	mkdir -p obj mod
	$(FC) $(FFLAGS) -shared -module mod -o libzfit.so src/minpack.f90 src/global.f90 src/laser.f90 src/chem.f90 src/zfit.f90 src/opkdmain.f src/opkda1.f src/opkda2.f $(LDFLAGS)

clean:
	rm -rf obj mod
	rm -f libzfit.so libzfit.a *.mod
