name: Publish to PyPI

on:
  workflow_run:
    workflows: [Build Wheels, Build Wheels (Intel oneAPI)]
    types: [completed]

jobs:
  publish-zscan-fit:
    name: Publish zscan-fit (gfortran)
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v6
        with:
          name: wheels-zscan-fit-linux-x86_64
          path: dist

      - name: Download aarch64 wheels
        uses: actions/download-artifact@v6
        with:
          name: wheels-zscan-fit-linux-aarch64
          path: dist

      - name: Download windows wheels
        uses: actions/download-artifact@v6
        with:
          name: wheels-zscan-fit-windows
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-zscan-fit-intel:
    name: Publish zscan-fit-intel (Intel)
    needs: publish-zscan-fit
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download linux wheels
        uses: actions/download-artifact@v6
        with:
          name: wheels-zscan-fit-intel-linux
          path: dist

      - name: Download windows wheels
        uses: actions/download-artifact@v6
        with:
          name: wheels-zscan-fit-intel-windows
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
